version: 2
jobs:
  build:
    working_directory: ~/meme_creator
    docker:
      - image: circleci/python:3.7.5
        environment:
          PIPENV_VENV_IN_PROJECT: true
          PIPENV_DONT_LOAD_ENV: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    environment:
      DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run: cp .env.template .env
      - restore_cache:
          key: v1-python37-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            make dependencies
      - save_cache:
          key: v1-python37-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run: make test
